module.exports.terms = [
    'Affogato',
    'Americano',
    'Boba',
    'Cappuccino',
    'Cold Brew',
    'Cortado',
    'Doppio',
    'Double Espresso',
    'Espresso',
    'Flat White',
    'Frappe',
    'Latte',
    'Macchiato',
    'Milk Tea',
    'Mocha',
    'Nitro',
    'Pour Over',
    'Red Eye',
    'Ristretto',
    'Vienna'
];

module.exports.places = [
    'Cafe',
    'Bar',
    'Place',
    'Stop',
    'Drive',
    'Shop',
    'House',
    'Room',
    'Lounge',
    'Club',
    'Parlor',
    'Corner',
    'Nook',
    'Street',
    'City'
];